# Generated by Django 4.1.3 on 2022-12-02 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('bookid', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('booktitle', models.CharField(max_length=100)),
                ('bookname', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('booknumber', models.CharField(max_length=100)),
                ('pubdate', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='borrowing',
            fields=[
                ('borrowingid', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('dateborrowed', models.CharField(max_length=100)),
                ('datereturn', models.CharField(max_length=100)),
                ('bookid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lib.book')),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('studentid', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('contactadd', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('studentpassword', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('transactionid', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('transname', models.CharField(max_length=100)),
                ('transdate', models.CharField(max_length=100)),
                ('borrowingid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lib.borrowing')),
                ('studentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lib.student')),
            ],
        ),
        migrations.CreateModel(
            name='reports',
            fields=[
                ('reportid', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('reportdate', models.CharField(max_length=100)),
                ('borrowingid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lib.borrowing')),
                ('transid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lib.transaction')),
            ],
        ),
        migrations.AddField(
            model_name='borrowing',
            name='studentid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lib.student'),
        ),
    ]
