# Generated by Django 3.2.14 on 2022-12-02 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('passwd', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='reports',
            name='borrowingid',
        ),
        migrations.RemoveField(
            model_name='reports',
            name='transid',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='borrowingid',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='studentid',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='bookid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='fname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='lname',
        ),
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='borrowing',
        ),
        migrations.DeleteModel(
            name='reports',
        ),
        migrations.DeleteModel(
            name='transaction',
        ),
    ]
