# Generated by Django 3.2.14 on 2022-12-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0004_book_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookt',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
